const FETCH_ALL_CATEGORIES_SUCCESS = "@CATEGORY/FETCH_ALL_SUCCESS";

const FETCH_ALL_CATEGORIES = "@CATEGORY/FETCH_ALL";

const FETCH_ALL_CATEGORIES_ERROR = "@CATEGORY/FETCH_ALL_ERROR";

export default {
  FETCH_ALL_CATEGORIES_SUCCESS,
  FETCH_ALL_CATEGORIES,
  FETCH_ALL_CATEGORIES_ERROR,
} as const;
