const FETCH_ALL_STORES_SUCCESS = "@STORE/FETCH_ALL_SUCCESS";

const FETCH_ALL_STORES = "@STORE/FETCH_ALL";

const FETCH_ALL_STORES_ERROR = "@STORE/FETCH_ALL_ERROR";

export default {
  FETCH_ALL_STORES_SUCCESS,
  FETCH_ALL_STORES,
  FETCH_ALL_STORES_ERROR,
} as const;
