const GET_ALL_STORES = '@STORE/GETALL'

const SET_ALL_STORES = '@STORE/SETALL'

const SET_ALL_STORES_ERROR = '@STORE/SETALLERROR'

const GET_STORE = '@STORE/GET'

export default {
	GET_ALL_STORES,
	GET_STORE,
	SET_ALL_STORES,
	SET_ALL_STORES_ERROR
} as const
