const FETCH_ALL_STORES_SUCCESS = "@STORE/FETCH_ALL_SUCCESS";

const FETCH_ALL_STORES = "@STORE/FETCH_ALL";

const FETCH_ALL_STORES_ERROR = "@STORE/FETCH_ALL_ERROR";

const SET_ALL_STORES = "@STORE/SETALL";

const SET_ALL_STORES_ERROR = "@STORE/SETALLERROR";

const GET_STORE = "@STORE/GET";

export default {
  FETCH_ALL_STORES_SUCCESS,
  FETCH_ALL_STORES,
  FETCH_ALL_STORES_ERROR,
  GET_STORE,
  SET_ALL_STORES,
  SET_ALL_STORES_ERROR,
} as const;
