const FETCH_ALL_COUPONS_SUCCESS = "@COUPON/FETCH_ALL_SUCCESS";

const FETCH_ALL_COUPONS = "@COUPON/FETCH_ALL";

const FETCH_ALL_COUPONS_ERROR = "@COUPON/FETCH_ALL_ERROR";

export default {
  FETCH_ALL_COUPONS_SUCCESS,
  FETCH_ALL_COUPONS,
  FETCH_ALL_COUPONS_ERROR,
} as const;
